# Generated by Django 5.2.16 on 2026-07-30 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('room_type', models.CharField(choices=[('lecture', 'Lecture'), ('laboratory', 'Laboratory'), ('specialized', 'Specialized')], max_length=12)),
                ('capacity', models.PositiveIntegerField()),
                ('restricted_to_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restricted_rooms', to='core.department')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=9)),
                ('term_name', models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('summer', 'Summer')], max_length=6)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-academic_year', 'term_name'],
                'constraints': [models.UniqueConstraint(fields=('academic_year', 'term_name'), name='unique_academic_term')],
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_code', models.CharField(max_length=10)),
                ('year_level', models.PositiveSmallIntegerField()),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='academics.curriculum')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='scheduling.term')),
            ],
            options={
                'ordering': ['curriculum', 'year_level', 'section_code'],
                'constraints': [models.UniqueConstraint(fields=('curriculum', 'term', 'section_code', 'year_level'), name='unique_block_section_per_term')],
            },
        ),
    ]
