# Generated by Django 5.2.16 on 2026-07-30 01:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('faculty', '0001_initial'),
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday')], max_length=3)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'ordering': ('day_of_week', 'start_time', 'end_time'),
                'constraints': [models.UniqueConstraint(fields=('day_of_week', 'start_time', 'end_time'), name='unique_time_slot')],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units_credited', models.DecimalField(decimal_places=1, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_of_week', models.CharField(editable=False, max_length=3)),
                ('start_time', models.TimeField(editable=False)),
                ('end_time', models.TimeField(editable=False)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='scheduling.block')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assignments', to=settings.AUTH_USER_MODEL)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='faculty.faculty')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='scheduling.room')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='academics.subject')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='scheduling.term')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='scheduling.timeslot')),
            ],
            options={
                'ordering': ('term', 'day_of_week', 'start_time', 'block'),
            },
        ),
    ]
