# Generated by Django 5.2.16 on 2026-09-11 06:43

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_college_options_college_created_by_and_more'),
        ('faculty', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={'ordering': ['last_name', 'first_name'], 'permissions': [('activate_faculty', 'Can activate or deactivate faculty')]},
        ),
        migrations.AddField(
            model_name='faculty',
            name='contact_number',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='faculty',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='faculty',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='faculty',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='faculty',
            name='maximum_load',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='faculty',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='faculty',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='recommended_load',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='faculty',
            name='suffix',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='faculty',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='base_load_units',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='employment_type',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.CreateModel(
            name='AcademicRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='faculty',
            name='academic_rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='faculty.academicrank'),
        ),
        migrations.CreateModel(
            name='EmploymentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='faculty',
            name='employment_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='faculty.employmentcategory'),
        ),
        migrations.AddConstraint(
            model_name='faculty',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('employee_id'), name='faculty_employee_id_case_unique'),
        ),
        migrations.AddConstraint(
            model_name='faculty',
            constraint=models.CheckConstraint(condition=models.Q(('recommended_load__isnull', True), ('recommended_load__gte', 0), _connector='OR'), name='faculty_recommended_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='faculty',
            constraint=models.CheckConstraint(condition=models.Q(('maximum_load__isnull', True), ('maximum_load__gte', 0), _connector='OR'), name='faculty_maximum_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='faculty',
            constraint=models.CheckConstraint(condition=models.Q(('recommended_load__isnull', True), ('maximum_load__isnull', True), ('recommended_load__lte', models.F('maximum_load')), _connector='OR'), name='faculty_capacity_ordered'),
        ),
        migrations.AddConstraint(
            model_name='faculty',
            constraint=models.CheckConstraint(condition=models.Q(('base_load_units__gte', 0)), name='faculty_legacy_load_nonnegative'),
        ),
    ]
