# Generated by Django 5.2.17 on 2026-09-30 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_alter_faculty_options_faculty_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={'ordering': ['last_name', 'first_name'], 'permissions': [('activate_faculty', 'Can activate or deactivate faculty'), ('view_own_teaching', 'Can view and download own published teaching records')]},
        ),
    ]
