# Generated by Django 5.2.16 on 2026-07-30 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='role',
            field=models.CharField(choices=[('department_admin', 'Department admin'), ('dept_chair', 'Department chair'), ('dean', 'Dean'), ('super_admin', 'Super admin')], max_length=20),
        ),
    ]
