# Generated by Django 5.2.16 on 2026-09-11 05:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def migrate_scopes(apps, schema_editor):
    Profile = apps.get_model('accounts', 'AdminProfile')
    Profile.objects.filter(role='department_admin').update(role='staff')
    # A legacy dean had campus-wide access and no college. Never guess a college.
    Profile.objects.filter(role='dean').update(is_enabled=False)
    Profile.objects.filter(role__in=['staff', 'dept_chair'], department__isnull=True).update(is_enabled=False)
    Profile.objects.filter(role='super_admin', department__isnull=False).update(is_enabled=False)
    Profile.objects.exclude(role__in=['super_admin', 'dean', 'dept_chair', 'staff']).update(role='staff', is_enabled=False)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_adminprofile_role'),
        ('core', '0002_alter_college_options_college_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='administrators', to='core.college'),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='is_enabled',
            field=models.BooleanField(default=True, help_text='Disabled profiles cannot access the application.'),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='role',
            field=models.CharField(choices=[('super_admin', 'System Admin'), ('dean', 'College Dean'), ('dept_chair', 'Department Chair'), ('staff', 'Authorized Staff')], max_length=20),
        ),
        migrations.RunPython(migrate_scopes, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='adminprofile',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['super_admin', 'dean', 'dept_chair', 'staff'])), name='profile_known_role'),
        ),
        migrations.AddConstraint(
            model_name='adminprofile',
            constraint=models.CheckConstraint(condition=models.Q(('is_enabled', False), models.Q(('college__isnull', True), ('department__isnull', True), ('role', 'super_admin')), models.Q(('college__isnull', False), ('department__isnull', True), ('role', 'dean')), models.Q(('college__isnull', True), ('department__isnull', False), ('role', 'dept_chair')), models.Q(('role', 'staff'), models.Q(models.Q(('college__isnull', False), ('department__isnull', True)), models.Q(('college__isnull', True), ('department__isnull', False)), _connector='OR')), _connector='OR'), name='profile_valid_organizational_scope'),
        ),
    ]
