# Generated by Django 5.2.17 on 2026-09-30 06:58

from django.conf import settings
from django.db import migrations, models


def migrate_roles(apps, schema_editor):
    database = schema_editor.connection.alias
    Profile = apps.get_model('accounts', 'AdminProfile')
    Audit = apps.get_model('audit', 'AuditLog')
    for profile in Profile.objects.using(database).filter(role__in=['dean', 'dept_chair']).iterator():
        previous = profile.role
        Profile.objects.using(database).filter(pk=profile.pk).update(role='staff')
        Audit.objects.using(database).create(action='account.role_migrated',
            object_type='accounts.AdminProfile', object_id=str(profile.pk),
            college_id=profile.college_id, department_id=profile.department_id,
            details={'previous_role': previous, 'role': 'staff', 'user_id': profile.user_id,
                     'is_enabled': profile.is_enabled})


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_loginfailurebucket'),
        ('audit', '0001_initial'),
        ('core', '0003_college_export_report_permission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='adminprofile',
            name='profile_known_role',
        ),
        migrations.RemoveConstraint(
            model_name='adminprofile',
            name='profile_valid_organizational_scope',
        ),
        migrations.RunPython(migrate_roles, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='adminprofile',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Admin'), ('staff', 'Authorized Staff'), ('faculty', 'Faculty')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='adminprofile',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['super_admin', 'staff', 'faculty'])), name='profile_known_role'),
        ),
        migrations.AddConstraint(
            model_name='adminprofile',
            constraint=models.CheckConstraint(condition=models.Q(('is_enabled', False), models.Q(('college__isnull', True), ('department__isnull', True), ('role', 'super_admin')), models.Q(('college__isnull', True), ('department__isnull', True), ('role', 'faculty')), models.Q(('role', 'staff'), models.Q(models.Q(('college__isnull', False), ('department__isnull', True)), models.Q(('college__isnull', True), ('department__isnull', False)), _connector='OR')), _connector='OR'), name='profile_valid_organizational_scope'),
        ),
    ]
