# Generated by Django 5.2.16 on 2026-09-12 07:02

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0006_alter_subject_options_subject_created_at_and_more'),
        ('core', '0002_alter_college_options_college_created_by_and_more'),
        ('resources', '0002_preserve_legacy_categories'),
        ('scheduling', '0006_alter_room_options_room_building_room_category_and_more'),
        ('workloads', '0002_facultytermcapacity_enforce_maximum_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40)),
                ('year_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('expected_size', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.academicterm')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.department')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.program')),
            ],
            options={
                'ordering': ['code', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='OfferingRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_type_mandatory', models.BooleanField(default=False)),
                ('capacity_is_hard', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('room_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='resources.roomtype')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offering_requirements', to='timetabling.classsection')),
                ('subject_offering', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='scheduling_requirement', to='workloads.subjectoffering')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoomUnavailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('notes', models.TextField(blank=True)),
                ('academic_term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.academicterm')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unavailable_periods', to='scheduling.room')),
            ],
            options={
                'ordering': ['day_of_week', 'start_time', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('validated', 'Validated')], default='draft', editable=False, max_length=12)),
                ('validated_signature', models.CharField(blank=True, editable=False, max_length=64)),
                ('academic_term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.academicterm')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.department')),
            ],
            options={
                'ordering': ['-academic_term__start_date', 'name', 'pk'],
                'permissions': [('validate_schedule', 'Can validate a manual schedule')],
            },
        ),
        migrations.CreateModel(
            name='ScheduleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('notes', models.TextField(blank=True)),
                ('meeting_type', models.CharField(choices=[('lecture', 'Lecture'), ('laboratory', 'Laboratory')], max_length=12)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meetings', to='workloads.facultysubjectassignment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meetings', to='scheduling.room')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='timetabling.schedule')),
            ],
            options={
                'ordering': ['day_of_week', 'start_time', 'pk'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='classsection',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), models.F('academic_term'), models.F('department'), name='section_code_term_department'),
        ),
        migrations.AddConstraint(
            model_name='roomunavailability',
            constraint=models.CheckConstraint(condition=models.Q(('start_time__lt', models.F('end_time'))), name='roomunavailability_ordered_times'),
        ),
        migrations.AddConstraint(
            model_name='roomunavailability',
            constraint=models.CheckConstraint(condition=models.Q(('day_of_week__gte', 1), ('day_of_week__lte', 7)), name='roomunavailability_valid_weekday'),
        ),
        migrations.AddConstraint(
            model_name='roomunavailability',
            constraint=models.UniqueConstraint(fields=('room', 'academic_term', 'day_of_week', 'start_time', 'end_time'), name='room_closure_unique'),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'validated'])), name='manual_schedule_known_status'),
        ),
        migrations.AddConstraint(
            model_name='scheduleentry',
            constraint=models.CheckConstraint(condition=models.Q(('start_time__lt', models.F('end_time'))), name='scheduleentry_ordered_times'),
        ),
        migrations.AddConstraint(
            model_name='scheduleentry',
            constraint=models.CheckConstraint(condition=models.Q(('day_of_week__gte', 1), ('day_of_week__lte', 7)), name='scheduleentry_valid_weekday'),
        ),
        migrations.AddConstraint(
            model_name='scheduleentry',
            constraint=models.CheckConstraint(condition=models.Q(('meeting_type__in', ['lecture', 'laboratory'])), name='meeting_known_type'),
        ),
    ]
