# Generated by Django 5.2.16 on 2026-09-15 07:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_alter_subject_options_subject_created_at_and_more'),
        ('core', '0002_alter_college_options_college_created_by_and_more'),
        ('timetabling', '0001_initial'),
        ('workloads', '0002_facultytermcapacity_enforce_maximum_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['-academic_term__start_date', 'name', 'pk'], 'permissions': [('validate_schedule', 'Can validate a manual schedule'), ('generate_schedule', 'Can generate a schedule')]},
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='is_locked',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ScheduleGenerationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('strategy', models.CharField(choices=[('FILL_GAPS', 'Fill gaps'), ('REPLACE_UNLOCKED', 'Replace unlocked meetings')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('PROPOSAL_READY', 'Proposal ready'), ('ACCEPTED', 'Accepted'), ('DISCARDED', 'Discarded'), ('INPUT_INVALID', 'Input invalid'), ('INFEASIBLE', 'Infeasible'), ('STALE', 'Stale'), ('VALIDATION_FAILED', 'Validation failed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('solver_status', models.CharField(blank=True, choices=[('OPTIMAL', 'Optimal'), ('FEASIBLE', 'Feasible'), ('INFEASIBLE', 'Infeasible'), ('MODEL_INVALID', 'Model invalid'), ('UNKNOWN', 'Unknown')], default='', max_length=20)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('started_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('finished_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('discarded_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('solver_time_limit_seconds', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('runtime_seconds', models.FloatField(blank=True, editable=False, null=True)),
                ('objective_value', models.FloatField(blank=True, editable=False, null=True)),
                ('best_bound', models.FloatField(blank=True, editable=False, null=True)),
                ('configuration_snapshot', models.JSONField(default=dict, editable=False)),
                ('input_summary', models.JSONField(default=dict, editable=False)),
                ('source_signature', models.CharField(blank=True, editable=False, max_length=64)),
                ('proposed_meetings', models.JSONField(default=list, editable=False)),
                ('penalty_breakdown', models.JSONField(default=dict, editable=False)),
                ('diagnostics', models.JSONField(default=list, editable=False)),
                ('solver_statistics', models.JSONField(default=dict, editable=False)),
                ('proposed_meeting_count', models.PositiveIntegerField(default=0, editable=False)),
                ('accepted_meeting_count', models.PositiveIntegerField(default=0, editable=False)),
                ('academic_term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.academicterm')),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accepted_schedule_generation_runs', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.department')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_schedule_generation_runs', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generation_runs', to='timetabling.schedule')),
            ],
            options={
                'ordering': ['-requested_at', '-pk'],
            },
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='generation_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='generated_entries', to='timetabling.schedulegenerationrun'),
        ),
        migrations.CreateModel(
            name='SchedulingConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_weekdays', models.JSONField()),
                ('earliest_start', models.TimeField()),
                ('latest_end', models.TimeField()),
                ('slot_increment_minutes', models.PositiveSmallIntegerField()),
                ('solver_time_limit_seconds', models.PositiveIntegerField()),
                ('random_seed', models.IntegerField()),
                ('worker_count', models.PositiveSmallIntegerField()),
                ('faculty_preference_weight', models.PositiveIntegerField(default=0)),
                ('faculty_gap_weight', models.PositiveIntegerField(default=0)),
                ('section_gap_weight', models.PositiveIntegerField(default=0)),
                ('meeting_distribution_weight', models.PositiveIntegerField(default=0)),
                ('room_fit_weight', models.PositiveIntegerField(default=0)),
                ('academic_term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.academicterm')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.department')),
            ],
            options={
                'ordering': ['-academic_term__start_date', 'department', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentMeetingRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting_type', models.CharField(choices=[('lecture', 'Lecture'), ('laboratory', 'Laboratory')], max_length=12)),
                ('meetings_per_week', models.PositiveSmallIntegerField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meeting_requirements', to='workloads.facultysubjectassignment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['assignment', 'meeting_type', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('assignment', 'meeting_type'), name='assignment_meeting_type_unique'), models.CheckConstraint(condition=models.Q(('meetings_per_week__gt', 0)), name='meeting_requirement_count_positive'), models.CheckConstraint(condition=models.Q(('duration_minutes__gt', 0)), name='meeting_requirement_duration_positive')],
            },
        ),
        migrations.AddConstraint(
            model_name='schedulegenerationrun',
            constraint=models.CheckConstraint(condition=models.Q(('strategy__in', ['FILL_GAPS', 'REPLACE_UNLOCKED'])), name='generation_run_known_strategy'),
        ),
        migrations.AddConstraint(
            model_name='schedulegenerationrun',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['PENDING', 'RUNNING', 'PROPOSAL_READY', 'ACCEPTED', 'DISCARDED', 'INPUT_INVALID', 'INFEASIBLE', 'STALE', 'VALIDATION_FAILED', 'FAILED'])), name='generation_run_known_status'),
        ),
        migrations.AddConstraint(
            model_name='schedulegenerationrun',
            constraint=models.CheckConstraint(condition=models.Q(('solver_status__in', ['', 'OPTIMAL', 'FEASIBLE', 'INFEASIBLE', 'MODEL_INVALID', 'UNKNOWN'])), name='generation_run_known_solver_status'),
        ),
        migrations.AddConstraint(
            model_name='schedulegenerationrun',
            constraint=models.CheckConstraint(condition=models.Q(('solver_time_limit_seconds__isnull', True), models.Q(('solver_time_limit_seconds__gt', 0), ('solver_time_limit_seconds__lte', 300)), _connector='OR'), name='generation_run_time_limit'),
        ),
        migrations.AddConstraint(
            model_name='schedulegenerationrun',
            constraint=models.CheckConstraint(condition=models.Q(('proposed_meeting_count__gte', 0)), name='generation_run_proposed_count_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='schedulegenerationrun',
            constraint=models.CheckConstraint(condition=models.Q(('accepted_meeting_count__gte', 0)), name='generation_run_accepted_count_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='schedulingconfiguration',
            constraint=models.UniqueConstraint(fields=('academic_term', 'department'), name='scheduling_configuration_term_department_unique'),
        ),
        migrations.AddConstraint(
            model_name='schedulingconfiguration',
            constraint=models.CheckConstraint(condition=models.Q(('earliest_start__lt', models.F('latest_end'))), name='scheduling_configuration_ordered_times'),
        ),
        migrations.AddConstraint(
            model_name='schedulingconfiguration',
            constraint=models.CheckConstraint(condition=models.Q(('slot_increment_minutes__gt', 0)), name='scheduling_configuration_slot_positive'),
        ),
        migrations.AddConstraint(
            model_name='schedulingconfiguration',
            constraint=models.CheckConstraint(condition=models.Q(('solver_time_limit_seconds__gt', 0), ('solver_time_limit_seconds__lte', 300)), name='scheduling_configuration_time_limit'),
        ),
        migrations.AddConstraint(
            model_name='schedulingconfiguration',
            constraint=models.CheckConstraint(condition=models.Q(('worker_count__gt', 0), ('worker_count__lte', 64)), name='scheduling_configuration_worker_count'),
        ),
        migrations.AddConstraint(
            model_name='schedulingconfiguration',
            constraint=models.CheckConstraint(condition=models.Q(('faculty_preference_weight__gte', 0)), name='scheduling_faculty_preference_weight_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='schedulingconfiguration',
            constraint=models.CheckConstraint(condition=models.Q(('faculty_gap_weight__gte', 0)), name='scheduling_faculty_gap_weight_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='schedulingconfiguration',
            constraint=models.CheckConstraint(condition=models.Q(('section_gap_weight__gte', 0)), name='scheduling_section_gap_weight_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='schedulingconfiguration',
            constraint=models.CheckConstraint(condition=models.Q(('meeting_distribution_weight__gte', 0)), name='scheduling_meeting_distribution_weight_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='schedulingconfiguration',
            constraint=models.CheckConstraint(condition=models.Q(('room_fit_weight__gte', 0)), name='scheduling_room_fit_weight_nonnegative'),
        ),
    ]
