# Generated by Django 5.2.17 on 2026-09-24 01:46

import django.contrib.postgres.constraints
import django.db.models.deletion
import django.utils.timezone
import timetabling.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_alter_subject_options_subject_created_at_and_more'),
        ('core', '0002_alter_college_options_college_created_by_and_more'),
        ('faculty', '0002_alter_faculty_options_faculty_contact_number_and_more'),
        ('scheduling', '0006_alter_room_options_room_building_room_category_and_more'),
        ('timetabling', '0003_scheduling_dependency_lock_triggers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='OfficialResourceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'ordering': ['booking_date', 'start_time', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleApprovalSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_token', models.CharField(max_length=32)),
                ('dependency_signature', models.CharField(max_length=64)),
                ('approved_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('payload', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ['-academic_term__start_date', 'name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleWorkflowEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submitted', 'Submitted'), ('resubmitted', 'Resubmitted'), ('returned', 'Returned for revision'), ('approved', 'Approved'), ('replaced', 'Official schedule replaced'), ('revised', 'Revision created')], max_length=16)),
                ('revision_token', models.CharField(max_length=32)),
                ('remarks', models.TextField(blank=True)),
                ('warning_codes', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['-academic_term__start_date', 'name', 'pk'], 'permissions': [('validate_schedule', 'Can validate a manual schedule'), ('generate_schedule', 'Can generate a schedule'), ('submit_schedule', 'Can submit a schedule for review'), ('review_schedule', 'Can review a submitted schedule'), ('approve_schedule', 'Can approve a submitted schedule'), ('revise_schedule', 'Can revise an approved schedule')]},
        ),
        migrations.RemoveConstraint(
            model_name='schedule',
            name='manual_schedule_known_status',
        ),
        migrations.AddField(
            model_name='schedule',
            name='parent_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='timetabling.schedule'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='revision_token',
            field=models.CharField(default=timetabling.models.new_revision_token, editable=False, max_length=32),
        ),
        migrations.AddField(
            model_name='schedule',
            name='submitted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schedule',
            name='submitted_revision_token',
            field=models.CharField(blank=True, editable=False, max_length=32),
        ),
        migrations.AddField(
            model_name='schedule',
            name='submitted_signature',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='schedule',
            name='submitted_warning_codes',
            field=models.JSONField(default=list, editable=False),
        ),
        migrations.AddField(
            model_name='schedule',
            name='version_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('validated', 'Validated'), ('under_review', 'Under review'), ('needs_revision', 'Needs revision'), ('approved', 'Approved')], default='draft', editable=False, max_length=16),
        ),
        migrations.AddField(
            model_name='activeschedule',
            name='academic_term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.academicterm'),
        ),
        migrations.AddField(
            model_name='activeschedule',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.department'),
        ),
        migrations.AddField(
            model_name='activeschedule',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='active_selections', to='timetabling.schedule'),
        ),
        migrations.AddField(
            model_name='activeschedule',
            name='selected_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selected_official_schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='officialresourcebooking',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='faculty.faculty'),
        ),
        migrations.AddField(
            model_name='officialresourcebooking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scheduling.room'),
        ),
        migrations.AddField(
            model_name='officialresourcebooking',
            name='schedule_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='official_bookings', to='timetabling.scheduleentry'),
        ),
        migrations.AddField(
            model_name='officialresourcebooking',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='timetabling.classsection'),
        ),
        migrations.AddField(
            model_name='scheduleapprovalsnapshot',
            name='approved_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_approval_snapshots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scheduleapprovalsnapshot',
            name='schedule',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='approval_snapshot', to='timetabling.schedule'),
        ),
        migrations.AddField(
            model_name='schedulefamily',
            name='academic_term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.academicterm'),
        ),
        migrations.AddField(
            model_name='schedulefamily',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schedulefamily',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.department'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='timetabling.schedulefamily'),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'validated', 'under_review', 'needs_revision', 'approved'])), name='manual_schedule_known_status'),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.CheckConstraint(condition=models.Q(('version_number__gt', 0)), name='schedule_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(fields=('family', 'version_number'), name='schedule_family_version_unique'),
        ),
        migrations.AddField(
            model_name='scheduleworkflowevent',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_workflow_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scheduleworkflowevent',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workflow_events', to='timetabling.schedule'),
        ),
        migrations.AddConstraint(
            model_name='activeschedule',
            constraint=models.UniqueConstraint(fields=('academic_term', 'department'), name='active_schedule_term_department_unique'),
        ),
        migrations.AddConstraint(
            model_name='officialresourcebooking',
            constraint=models.CheckConstraint(condition=models.Q(('start_time__lt', models.F('end_time'))), name='official_booking_ordered_times'),
        ),
        migrations.AddConstraint(
            model_name='officialresourcebooking',
            constraint=models.UniqueConstraint(fields=('schedule_entry', 'booking_date'), name='official_booking_entry_date_unique'),
        ),
        migrations.AddConstraint(
            model_name='officialresourcebooking',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(expressions=[('faculty', '='), ('booking_date', '='), (timetabling.models.BookingTimeRange('start_time', 'end_time'), '&&')], name='official_faculty_booking_no_overlap'),
        ),
        migrations.AddConstraint(
            model_name='officialresourcebooking',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(expressions=[('room', '='), ('booking_date', '='), (timetabling.models.BookingTimeRange('start_time', 'end_time'), '&&')], name='official_room_booking_no_overlap'),
        ),
        migrations.AddConstraint(
            model_name='officialresourcebooking',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(expressions=[('section', '='), ('booking_date', '='), (timetabling.models.BookingTimeRange('start_time', 'end_time'), '&&')], name='official_section_booking_no_overlap'),
        ),
        migrations.AddConstraint(
            model_name='scheduleworkflowevent',
            constraint=models.CheckConstraint(condition=models.Q(('action__in', ['submitted', 'resubmitted', 'returned', 'approved', 'replaced', 'revised'])), name='schedule_workflow_known_action'),
        ),
    ]
