# Generated by Django 5.2.17 on 2026-09-24 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetabling', '0005_phase7_backfill_and_integrity'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='submitted_active_schedule',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='timetabling.schedule'),
        ),
    ]
