# Generated by Django 5.2.17 on 2026-09-30 06:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetabling', '0007_protect_active_official_bookings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE TRIGGER timetabling_scheduling_dependency_lock BEFORE INSERT OR UPDATE OR DELETE ON timetabling_activeschedule FOR EACH STATEMENT EXECUTE FUNCTION timetabling_acquire_scheduling_lock();",
            "DROP TRIGGER timetabling_scheduling_dependency_lock ON timetabling_activeschedule;",
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['-academic_term__start_date', 'name', 'pk'], 'permissions': [('validate_schedule', 'Can validate a manual schedule'), ('generate_schedule', 'Can generate a schedule'), ('finalize_schedule', 'Can finalize and publish a schedule'), ('submit_schedule', 'Can submit a schedule for review'), ('review_schedule', 'Can review a submitted schedule'), ('approve_schedule', 'Can approve a submitted schedule'), ('revise_schedule', 'Can revise an approved schedule')]},
        ),
        migrations.RemoveConstraint(
            model_name='scheduleworkflowevent',
            name='schedule_workflow_known_action',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('validated', 'Validated'), ('under_review', 'Under review'), ('needs_revision', 'Needs revision'), ('approved', 'Published')], default='draft', editable=False, max_length=16),
        ),
        migrations.AlterField(
            model_name='scheduleworkflowevent',
            name='action',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('resubmitted', 'Resubmitted'), ('returned', 'Returned for revision'), ('approved', 'Approved'), ('replaced', 'Official schedule replaced'), ('revised', 'Revision created'), ('finalized', 'Finalized and published')], max_length=16),
        ),
        migrations.AddConstraint(
            model_name='scheduleworkflowevent',
            constraint=models.CheckConstraint(condition=models.Q(('action__in', ['submitted', 'resubmitted', 'returned', 'approved', 'replaced', 'revised', 'finalized'])), name='schedule_workflow_known_action'),
        ),
    ]
