# Generated by Django 5.2.16 on 2026-09-11 06:43

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0006_alter_subject_options_subject_created_at_and_more'),
        ('core', '0002_alter_college_options_college_created_by_and_more'),
        ('faculty', '0002_alter_faculty_options_faculty_contact_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyTermCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recommended_load', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('maximum_load', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True)),
                ('academic_term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.academicterm')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='term_capacities', to='faculty.faculty')),
            ],
            options={
                'ordering': ['academic_term', 'pk'],
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('recommended_load__isnull', True), ('recommended_load__gte', 0), _connector='OR'), name='workloads_facultytermcapacity_rec_positive'), models.CheckConstraint(condition=models.Q(('maximum_load__isnull', True), ('maximum_load__gte', 0), _connector='OR'), name='workloads_facultytermcapacity_max_positive'), models.CheckConstraint(condition=models.Q(('recommended_load__isnull', True), ('maximum_load__isnull', True), ('recommended_load__lte', models.F('maximum_load')), _connector='OR'), name='workloads_facultytermcapacity_ordered'), models.UniqueConstraint(fields=('faculty', 'academic_term'), name='capacity_faculty_term_unique')],
            },
        ),
        migrations.CreateModel(
            name='WorkloadPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recommended_load', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('maximum_load', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('lecture_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Workload units per lecture unit. Blank inherits a broader policy.', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('laboratory_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Workload units per laboratory unit. Blank inherits a broader policy.', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True)),
                ('academic_term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.academicterm')),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.college')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.department')),
            ],
            options={
                'ordering': ['academic_term', 'pk'],
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('recommended_load__isnull', True), ('recommended_load__gte', 0), _connector='OR'), name='workloads_workloadpolicy_rec_positive'), models.CheckConstraint(condition=models.Q(('maximum_load__isnull', True), ('maximum_load__gte', 0), _connector='OR'), name='workloads_workloadpolicy_max_positive'), models.CheckConstraint(condition=models.Q(('recommended_load__isnull', True), ('maximum_load__isnull', True), ('recommended_load__lte', models.F('maximum_load')), _connector='OR'), name='workloads_workloadpolicy_ordered'), models.CheckConstraint(condition=models.Q(('college__isnull', True), ('department__isnull', True), _connector='OR'), name='policy_single_scope'), models.CheckConstraint(condition=models.Q(('lecture_weight__isnull', True), ('lecture_weight__gte', 0), _connector='OR'), name='policy_lecture_nonnegative'), models.CheckConstraint(condition=models.Q(('laboratory_weight__isnull', True), ('laboratory_weight__gte', 0), _connector='OR'), name='policy_lab_nonnegative'), models.UniqueConstraint(condition=models.Q(('college__isnull', True), ('department__isnull', True)), fields=('academic_term',), name='policy_term_institution_unique'), models.UniqueConstraint(condition=models.Q(('college__isnull', False)), fields=('academic_term', 'college'), name='policy_term_college_unique'), models.UniqueConstraint(condition=models.Q(('department__isnull', False)), fields=('academic_term', 'department'), name='policy_term_department_unique')],
            },
        ),
    ]
