# Generated by Django 5.2.16 on 2026-09-12 00:37

import django.contrib.postgres.constraints
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import workloads.db_functions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_alter_subject_options_subject_created_at_and_more'),
        ('core', '0002_alter_college_options_college_created_by_and_more'),
        ('faculty', '0002_alter_faculty_options_faculty_contact_number_and_more'),
        ('workloads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Shared with legacy exclusion constraints: never drop the extension on rollback.
        migrations.RunSQL("CREATE EXTENSION IF NOT EXISTS btree_gist;", reverse_sql=migrations.RunSQL.noop),
        migrations.AddField(
            model_name='facultytermcapacity',
            name='enforce_maximum',
            field=models.BooleanField(blank=True, help_text='Override maximum enforcement for this faculty and term; unknown inherits policy.', null=True),
        ),
        migrations.AddField(
            model_name='workloadpolicy',
            name='enforce_maximum',
            field=models.BooleanField(blank=True, help_text='Yes blocks assignments above the effective maximum. No warns. Unknown inherits; if unconfigured, warnings only.', null=True),
        ),
        migrations.CreateModel(
            name='SubjectOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(default='MAIN', help_text='Offering identifier within this subject and term, e.g. MAIN or A.', max_length=30)),
                ('lecture_units', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('laboratory_units', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('lecture_hours', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('laboratory_hours', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('academic_term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.academicterm')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.department')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='term_offerings', to='academics.subject')),
            ],
            options={
                'ordering': ['subject__code', 'code', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='FacultySubjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('share', models.DecimalField(decimal_places=2, default=1, help_text="Fraction of this offering's teaching, greater than zero and at most 1. Total shares cannot exceed 1.", max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teaching_assignments', to='faculty.faculty')),
                ('subject_offering', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teaching_assignments', to='workloads.subjectoffering')),
            ],
            options={
                'ordering': ['faculty__last_name', 'pk'],
                'permissions': [('view_workload', 'Can monitor faculty teaching workloads')],
            },
        ),
        migrations.CreateModel(
            name='FacultyAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('availability_type', models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable (hard restriction)'), ('preferred', 'Preferred')], max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('academic_term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.academicterm')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='availability_records', to='faculty.faculty')),
            ],
            options={
                'ordering': ['day_of_week', 'start_time', 'pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(('start_time__lt', models.F('end_time'))), name='availability_ordered_times'), models.CheckConstraint(condition=models.Q(('day_of_week__gte', 1), ('day_of_week__lte', 7)), name='availability_valid_day'), models.CheckConstraint(condition=models.Q(('availability_type__in', ['available', 'unavailable', 'preferred'])), name='availability_valid_kind'), django.contrib.postgres.constraints.ExclusionConstraint(expressions=[('faculty', '='), ('academic_term', '='), ('day_of_week', '='), ('availability_type', '='), (workloads.db_functions.AvailabilityRange('start_time', 'end_time'), '&&')], name='availability_same_kind_no_overlap'), django.contrib.postgres.constraints.ExclusionConstraint(expressions=[('faculty', '='), ('academic_term', '='), ('day_of_week', '='), (models.Case(models.When(availability_type='unavailable', then=models.Value(True)), default=models.Value(False), output_field=models.BooleanField()), '<>'), (workloads.db_functions.AvailabilityRange('start_time', 'end_time'), '&&')], name='availability_hard_soft_no_overlap')],
            },
        ),
        migrations.AddConstraint(
            model_name='subjectoffering',
            constraint=models.UniqueConstraint(fields=('subject', 'academic_term', 'code'), name='offering_subject_term_code_unique'),
        ),
        migrations.AddConstraint(
            model_name='subjectoffering',
            constraint=models.CheckConstraint(condition=models.Q(('lecture_units__gte', 0)), name='offering_lecture_units_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='subjectoffering',
            constraint=models.CheckConstraint(condition=models.Q(('laboratory_units__gte', 0)), name='offering_laboratory_units_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='subjectoffering',
            constraint=models.CheckConstraint(condition=models.Q(('lecture_hours__gte', 0)), name='offering_lecture_hours_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='subjectoffering',
            constraint=models.CheckConstraint(condition=models.Q(('laboratory_hours__gte', 0)), name='offering_laboratory_hours_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='facultysubjectassignment',
            constraint=models.UniqueConstraint(fields=('faculty', 'subject_offering'), name='faculty_offering_assignment_unique'),
        ),
        migrations.AddConstraint(
            model_name='facultysubjectassignment',
            constraint=models.CheckConstraint(condition=models.Q(('share__gt', 0), ('share__lte', 1)), name='assignment_valid_share'),
        ),
    ]
