# Generated by Django 5.2.16 on 2026-09-23 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_alter_subject_options_subject_created_at_and_more'),
        ('core', '0002_alter_college_options_college_created_by_and_more'),
        ('workloads', '0002_facultytermcapacity_enforce_maximum_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkloadRecommendationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROPOSAL_READY', 'Proposal ready'), ('ACCEPTED', 'Accepted'), ('DISCARDED', 'Discarded'), ('INPUT_INVALID', 'Input invalid'), ('INFEASIBLE', 'Infeasible'), ('STALE', 'Stale'), ('VALIDATION_FAILED', 'Validation failed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('raw_solver_status', models.CharField(blank=True, choices=[('OPTIMAL', 'Optimal'), ('FEASIBLE', 'Feasible'), ('INFEASIBLE', 'Infeasible'), ('MODEL_INVALID', 'Model invalid'), ('UNKNOWN', 'Unknown')], default='', max_length=20)),
                ('source_signature', models.CharField(blank=True, default='', max_length=64)),
                ('proposed_assignments', models.JSONField(default=list)),
                ('input_summary', models.JSONField(default=dict)),
                ('comparison', models.JSONField(default=dict)),
                ('diagnostics', models.JSONField(default=list)),
                ('solver_stats', models.JSONField(default=dict)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('discarded_at', models.DateTimeField(blank=True, null=True)),
                ('academic_term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.academicterm')),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accepted_workload_recommendation_runs', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.department')),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiated_workload_recommendation_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'permissions': [('generate_workloadrecommendation', 'Can generate faculty workload recommendations')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['PENDING', 'PROPOSAL_READY', 'ACCEPTED', 'DISCARDED', 'INPUT_INVALID', 'INFEASIBLE', 'STALE', 'VALIDATION_FAILED', 'FAILED'])), name='workload_recommendation_known_status'), models.CheckConstraint(condition=models.Q(('raw_solver_status__in', ['', 'OPTIMAL', 'FEASIBLE', 'INFEASIBLE', 'MODEL_INVALID', 'UNKNOWN'])), name='workload_recommendation_known_solver_status')],
            },
        ),
    ]
