# Generated by Django 5.2.16 on 2026-07-30 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('core', '0001_initial'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='irregularenrollment',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irregular_enrollments', to='scheduling.term'),
        ),
        migrations.AddField(
            model_name='student',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='scheduling.block'),
        ),
        migrations.AddField(
            model_name='student',
            name='curriculum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academics.curriculum'),
        ),
        migrations.AddField(
            model_name='student',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='core.program'),
        ),
        migrations.AddField(
            model_name='irregularenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irregular_enrollments', to='academics.student'),
        ),
        migrations.AddField(
            model_name='subject',
            name='owning_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_subjects', to='core.department'),
        ),
        migrations.AddField(
            model_name='irregularenrollment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='irregular_enrollments', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='curriculumsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_subjects', to='academics.subject'),
        ),
        migrations.AddConstraint(
            model_name='curriculum',
            constraint=models.UniqueConstraint(fields=('program', 'version_year'), name='unique_curriculum_version_per_program'),
        ),
        migrations.AddConstraint(
            model_name='irregularenrollment',
            constraint=models.UniqueConstraint(fields=('student', 'subject', 'term'), name='unique_irregular_enrollment'),
        ),
        migrations.AddConstraint(
            model_name='curriculumsubject',
            constraint=models.UniqueConstraint(fields=('curriculum', 'subject', 'term', 'year_level'), name='unique_subject_placement_in_curriculum'),
        ),
    ]
