# Generated by Django 5.2.16 on 2026-07-30 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='required_room_type',
            field=models.CharField(blank=True, choices=[('lecture', 'Lecture'), ('laboratory', 'Laboratory'), ('specialized', 'Specialized')], max_length=12, null=True),
        ),
    ]
