# Generated by Django 5.2.16 on 2026-09-11 06:43

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.text
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_term_date_integrity'),
        ('core', '0002_alter_college_options_college_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['code'], 'permissions': [('activate_subject', 'Can activate or deactivate subjects')]},
        ),
        migrations.AddField(
            model_name='subject',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='subject',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subject',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='laboratory_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='subject',
            name='laboratory_units',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='subject',
            name='lecture_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='subject',
            name='lecture_units',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='subject',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='owning_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_subjects', to='core.department'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='units',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), name='subject_code_case_unique'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.CheckConstraint(condition=models.Q(('units__gte', 0)), name='subject_total_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.CheckConstraint(condition=models.Q(('lecture_units__isnull', True), ('lecture_units__gte', 0), _connector='OR'), name='subject_lecture_units_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.CheckConstraint(condition=models.Q(('laboratory_units__gte', 0)), name='subject_lab_units_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.CheckConstraint(condition=models.Q(('lecture_hours__gte', 0)), name='subject_lecture_hours_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.CheckConstraint(condition=models.Q(('laboratory_hours__gte', 0)), name='subject_lab_hours_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.CheckConstraint(condition=models.Q(('lecture_units__isnull', True), ('units', django.db.models.expressions.CombinedExpression(models.F('lecture_units'), '+', models.F('laboratory_units'))), _connector='OR'), name='subject_total_matches_components'),
        ),
    ]
